{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature (Always Latest)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  temperature\nFROM air_quality\nWHERE\n  record_datetime = (SELECT MAX(record_datetime) from air_quality)"
    }
   ]
  },
  {
   "title": "Humidity (Always Latest)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  humidity\nFROM air_quality\nWHERE\n  record_datetime = (SELECT MAX(record_datetime) from air_quality)"
    }
   ]
  },
  {
   "title": "CO2 (Always Latest)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  carbon_dioxide\nFROM air_quality\nWHERE\n  record_datetime = (SELECT MAX(record_datetime) from air_quality)"
    }
   ]
  },
  {
   "title": "PM2.5/Fine Dust (Always Latest)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  particulate_matter_2_5\nFROM air_quality\nWHERE\n  record_datetime = (SELECT MAX(record_datetime) from air_quality)"
    }
   ]
  },
  {
   "title": "Total volatile organic compounds (Always Latest)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  volatile_organic_compounds\nFROM air_quality\nWHERE\n  record_datetime = (SELECT MAX(record_datetime) from air_quality)"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_datetime,$__interval),\n  avg(temperature) AS \"temperature\"\nFROM air_quality\nWHERE\n  $__timeFilter(record_datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_datetime,$__interval),\n  avg(humidity) AS \"humidity\"\nFROM air_quality\nWHERE\n  $__timeFilter(record_datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_datetime,$__interval),\n  avg(carbon_dioxide) AS \"carbon_dioxide\"\nFROM air_quality\nWHERE\n  $__timeFilter(record_datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PM2.5/Fine Dust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_datetime,30s),\n  avg(particulate_matter_2_5) AS \"particulate_matter_2_5\"\nFROM air_quality\nWHERE\n  $__timeFilter(record_datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total volatile organic compounds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(record_datetime,$__interval),\n  avg(volatile_organic_compounds) AS \"volatile_organic_compounds\"\nFROM air_quality\nWHERE\n  $__timeFilter(record_datetime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}